service: convert-to-powerpoint-lambda

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    PDF4ME_API_KEY: ${env:PDF4ME_API_KEY}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
            - s3:DeleteObject
          Resource: 
            - "arn:aws:s3:::converttopowerpoint-input-bucket/*"
            - "arn:aws:s3:::converttopowerpoint-output-bucket/*"

functions:
  convertToPowerpoint:
    handler: convertToPowerpoint_lambda.handler
    events:
      - httpApi:
          path: /convert-to-powerpoint
          method: POST
      - s3:
          bucket: converttopowerpoint-input-bucket
          event: s3:ObjectCreated:*
          existing: true
    environment:
      OUTPUT_BUCKET: converttopowerpoint-output-bucket

resources:
  Resources:
    ConvertToPowerpointInputBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: converttopowerpoint-input-bucket
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true

    ConvertToPowerpointOutputBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: converttopowerpoint-output-bucket
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true

plugins:
  - serverless-offline