service: flatten-pdf-lambda

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    PDF4ME_API_KEY: ${env:PDF4ME_API_KEY}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
            - s3:DeleteObject
          Resource: 
            - "arn:aws:s3:::flattenpdf-input-bucket/*"
            - "arn:aws:s3:::flattenpdf-output-bucket/*"

functions:
  flattenPdf:
    handler: flattenPdf_lambda.handler
    events:
      - httpApi:
          path: /flatten-pdf
          method: POST
      - s3:
          bucket: flattenpdf-input-bucket
          event: s3:ObjectCreated:*
          existing: true
    environment:
      OUTPUT_BUCKET: flattenpdf-output-bucket

resources:
  Resources:
    FlattenPdfInputBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: flattenpdf-input-bucket
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true

    FlattenPdfOutputBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: flattenpdf-output-bucket
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true

plugins:
  - serverless-offline