service: convert-visio-lambda

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    PDF4ME_API_KEY: ${env:PDF4ME_API_KEY}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
            - s3:DeleteObject
          Resource: 
            - "arn:aws:s3:::convertvisio-input-bucket/*"
            - "arn:aws:s3:::convertvisio-output-bucket/*"

functions:
  convertVisio:
    handler: convertVisio_lambda.handler
    events:
      - httpApi:
          path: /convert-visio
          method: POST
      - s3:
          bucket: convertvisio-input-bucket
          event: s3:ObjectCreated:*
          existing: true
    environment:
      OUTPUT_BUCKET: convertvisio-output-bucket

resources:
  Resources:
    ConvertVisioInputBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: convertvisio-input-bucket
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true

    ConvertVisioOutputBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: convertvisio-output-bucket
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true

plugins:
  - serverless-offline