service: add-page-number-to-pdf-lambda

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    PDF4ME_API_KEY: ${env:PDF4ME_API_KEY}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
            - s3:DeleteObject
          Resource: 
            - "arn:aws:s3:::pdf-page-number-input-bucket/*"
            - "arn:aws:s3:::pdf-page-number-output-bucket/*"

functions:
  addPageNumberToPdf:
    handler: add_page_number_to_pdf_lambda.handler
    events:
      - httpApi:
          path: /add-page-number-to-pdf
          method: POST
      - s3:
          bucket: pdf-page-number-input-bucket
          event: s3:ObjectCreated:*
          existing: true
    environment:
      OUTPUT_BUCKET: pdf-page-number-output-bucket

resources:
  Resources:
    PdfPageNumberInputBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: pdf-page-number-input-bucket
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true

    PdfPageNumberOutputBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: pdf-page-number-output-bucket
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true

plugins:
  - serverless-offline 