service: parse-document-lambda

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    PDF4ME_API_KEY: ${env:PDF4ME_API_KEY}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
            - s3:DeleteObject
          Resource: 
            - "arn:aws:s3:::parsedocument-input-bucket/*"
            - "arn:aws:s3:::parsedocument-output-bucket/*"

functions:
  parseDocument:
    handler: parse_document_lambda.handler
    events:
      - httpApi:
          path: /parse-document
          method: POST
      - s3:
          bucket: parsedocument-input-bucket
          event: s3:ObjectCreated:*
          existing: true
    environment:
      OUTPUT_BUCKET: parsedocument-output-bucket

resources:
  Resources:
    ParseDocumentInputBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: parsedocument-input-bucket
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true

    ParseDocumentOutputBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: parsedocument-output-bucket
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true

plugins:
  - serverless-offline 